### ISSUE TITLE
Adapt to 12.1

### ISSUE THREAD

**Issue by tnwss** [danypava/MSI_MORTAR_B550_5600X-OpenCore#1]
Adapt to 12.1
6600xt

**Comment by danypava** [comment]
@tnwss I've been trying to boot 12.1 for a week, but it doesn't seem to be possible as of now. You need to downgrade the BIOS to be able to boot, but to a version that doesn't support ryzen 5xxx series processors, and it is useless for me since i have a 5600x.

I don't have a  6600XT, but it should be supported OOB thanks to Lilu + Whatevergreen. You will probably just need to adapt the shikigva value to enable HW accelleration, but as long as you don't try to boot Monterey it should work.
